# Generated by Django 5.2.7 on 2025-12-28 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotificationPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enable_push", models.BooleanField(default=True)),
                ("enable_sms", models.BooleanField(default=False)),
                ("enable_email", models.BooleanField(default=True)),
                ("notify_on_expense_created", models.BooleanField(default=True)),
                ("notify_on_refund_requested", models.BooleanField(default=True)),
                ("notify_on_refund_approved", models.BooleanField(default=True)),
                ("notify_on_refund_rejected", models.BooleanField(default=True)),
                ("notify_on_budget_exceeded", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
